FROM node:18-alpine3.18

WORKDIR /usr/src/app

COPY . .

ARG NEXT_PUBLIC_API_KEY
ARG NEXT_PUBLIC_API_URL

ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_KEY=$NEXT_PUBLIC_API_KEY

RUN npm install
RUN npm run build
CMD ["npm", "start"]
