name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set app version
        id: set_version
        run: echo "::set-output name=appver::$(node -e 'console.log(require("./package.json").version)')"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: login to hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN}}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: halitderya/kanban:${{ steps.set_version.outputs.appver }}-64
          platforms: linux/amd64
          file: ./Dockerfile

      - name: deploying
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker image pull halitderya/kanban:${{ steps.set_version.outputs.appver }}-64
            docker container stop kanban
            docker container rm kanban
            docker rmi halitderya/kanban:${{ steps.set_version.outputs.appver }}-64 --force
            docker container run -d --name kanban -p 80:3000 halitderya/kanban:${{ steps.set_version.outputs.appver }}-64
